config/routes.rb
full_path_glob = '(/*full_path)'

# allow plugins to prepend routes
Dir["{gems,vendor}/plugins/*/config/pre_routes.rb"].each { |pre_routes|
  load pre_routes
}

CanvasRails::Application.routes.draw do
  resources :submission_comments, only: :destroy

  resources :epub_exports, only: [:index]

  get 'inbox' => 'context#inbox'
  get 'oauth/redirect_proxy' => 'oauth_proxy#redirect_proxy'

  get 'conversations/unread' => 'conversations#index', as: :conversations_unread, redirect_scope: 'unread'
  get 'conversations/starred' => 'conversations#index', as: :conversations_starred, redirect_scope: 'starred'
  get 'conversations/sent' => 'conversations#index', as: :conversations_sent, redirect_scope: 'sent'
  get 'conversations/archived' => 'conversations#index', as: :conversations_archived, redirect_scope: 'archived'
  get 'conversations/find_recipients' => 'search#recipients'

  get 'search/recipients' => 'search#recipients'
  post 'conversations/mark_all_as_read' => 'conversations#mark_all_as_read'
  post 'conversations/watched_intro' => 'conversations#watched_intro'
  get 'conversations/batches' => 'conversations#batches', as: :conversation_batches
  post 'conversations/toggle_new_conversations' => 'conversations#toggle_new_conversations', as: :toggle_new_conversations
  resources :conversations, only: [:index, :show, :update, :create, :destroy] do
    post :add_recipients
    post :add_message
    post :remove_messages
  end

  post "/external_auth_observers/redirect_login" => 'login/external_auth_observers#redirect_login', as: :external_auth_validation

  # So, this will look like:
  # http://instructure.com/register/5R32s9iqwLK75Jbbj0
  match 'register/:nonce' => 'communication_channels#confirm', as: :registration_confirmation, via: [:get, :post]
  # deprecated
  get 'pseudonyms/:id/register/:nonce' => 'communication_channels#confirm', as: :registration_confirmation_deprecated
  post 'confirmations/:user_id/re_send(/:id)' => 'communication_channels#re_send_confirmation', as: :re_send_confirmation, id: nil
  match 'forgot_password' => 'pseudonyms#forgot_password', as: :forgot_password, via: [:get, :post]
  get 'pseudonyms/:pseudonym_id/change_password/:nonce' => 'pseudonyms#confirm_change_password', as: :confirm_change_password
  post 'pseudonyms/:pseudonym_id/change_password/:nonce' => 'pseudonyms#change_password', as: :change_password

  # callback urls for oauth authorization processes
  get 'oauth' => 'users#oauth'
  get 'oauth_success' => 'users#oauth_success'

  get 'mr/:id' => 'info#message_redirect', as: :message_redirect
  get 'help_links' => 'info#help_links'

  # These are just debug routes, but they make working on error pages easier,
  # and it shouldn't matter if a client stumbles across them
  get 'test_error' => 'info#test_error'

  concern :question_banks do
    resources :question_banks do
      post :bookmark
      post :reorder
      get :questions
      post :move_questions
      resources :assessment_questions
    end
  end

  concern :groups do
    resources :groups
    resources :group_categories, only: [:create, :update, :destroy]
    get 'group_unassigned_members' => 'groups#unassigned_members'
  end

  resources :group_categories do
    member do
      post 'clone_with_name'
    end
  end

  concern :files do
    resources :files do
      get 'inline' => 'files#text_show', as: :text_inline
      get 'download' => 'files#show', download: '1'
      get 'download.:type' => 'files#show', as: :typed_download, download: '1'
      get 'preview' => 'files#show', preview: '1'
      post 'inline_view' => 'files#show', inline: '1'
      get 'contents' => 'files#attachment_content', as: :attachment_content
      get 'file_preview' => 'file_previews#show'
      collection do
        get "folder#{full_path_glob}" => 'files#react_files', format: false
        get "search" => 'files#react_files', format: false
        get :quota
        post :reorder
      end
      get ':file_path' => 'files#show_relative', as: :relative_path, file_path: /.+/ #needs to stay below react_files route
    end
  end

  concern :file_images do
    get 'images' => 'files#images'
  end

  concern :relative_files do
    get 'file_contents/:file_path' => 'files#show_relative', as: :relative_file_path, file_path: /.+/
  end

  concern :folders do
    resources :folders do
      get :download
    end
  end

  concern :media do
    get 'media_download' => 'users#media_download'
  end

  concern :users do
    get 'users' => 'context#roster'
    get 'user_services' => 'context#roster_user_services'
    get 'users/:user_id/usage' => 'context#roster_user_usage', as: :user_usage
    get 'users/:id' => 'context#roster_user', as: :user
  end

  concern :announcements do
    resources :announcements
    post 'announcements/external_feeds' => 'announcements#create_external_feed'
    delete 'announcements/external_feeds/:id' => 'announcements#destroy_external_feed', as: :announcements_external_feed
  end

  concern :discussions do
    resources :discussion_topics, only: [:index, :new, :show, :edit, :destroy]
    get 'discussion_topics/:id/:extras' => 'discussion_topics#show', as: :map, extras: /.+/
    resources :discussion_entries
  end

  concern :pages do
    resources :wiki_pages, path: :pages, except: [:update, :destroy, :new], constraints: { id: %r{[^\/]+} } do
      get 'revisions' => 'wiki_pages#revisions', as: :revisions
    end

    get 'wiki' => 'wiki_pages#front_page', as: :wiki
    get 'wiki/:id' => 'wiki_pages#show_redirect', id: /[^\/]+/
    get 'wiki/:id/revisions' => 'wiki_pages#revisions_redirect', id: /[^\/]+/
    get 'wiki/:id/revisions/:revision_id' => 'wiki_pages#revisions_redirect', id: /[^\/]+/
  end

  concern :conferences do
    resources :conferences do
      match :join, via: [:get, :post]
      match :close, via: [:get, :post]
      get :settings
    end
  end

  concern :zip_file_imports do
    resources :zip_file_imports, only: [:new, :create, :show]
    get 'imports/files' => 'content_imports#files', as: :import_files
  end

  # There are a lot of resources that are all scoped to the course level
  # (assignments, files, wiki pages, user lists, forums, etc.).  Many of
  # these resources also apply to groups and individual users.  We call
  # courses, users, groups, or even accounts in this setting, "contexts".
  # There are some helper methods like the before_filter :get_context in application_controller
  # and the application_helper method :context_url to make retrieving
  # these contexts, and also generating context-specific urls, easier.
  resources :courses do
    # DEPRECATED
    get 'self_enrollment/:self_enrollment' => 'courses#self_enrollment', as: :self_enrollment
    post 'self_unenrollment/:self_unenrollment' => 'courses#self_unenrollment', as: :self_unenrollment
    post :restore
    post :backup
    post :unconclude
    get :students
    post :enrollment_invitation
    # this needs to come before the users concern, or users/:id will preempt it
    get 'users/prior' => 'context#prior_users', as: :prior_users
    concerns :users
    get :statistics
    delete 'unenroll/:id' => 'courses#unenroll_user', as: :unenroll
    post 'move_enrollment/:id' => 'courses#move_enrollment', as: :move_enrollment
    delete 'unenroll/:id.:format' => 'courses#unenroll_user', as: :formatted_unenroll
    post 'limit_user_grading/:id' => 'courses#limit_user', as: :limit_user_grading
    delete 'conclude_user/:id' => 'courses#conclude_user', as: :conclude_user_enrollment
    post 'unconclude_user/:id' => 'courses#unconclude_user', as: :unconclude_user_enrollment
    resources :sections, except: [:index, :edit, :new] do
      get 'crosslist/confirm/:new_course_id' => 'sections#crosslist_check', as: :confirm_crosslist
      post :crosslist
      delete 'crosslist' => 'sections#uncrosslist', as: :uncrosslist
    end

    get 'undelete' => 'context#undelete_index', as: :undelete_items
    post 'undelete/:asset_string' => 'context#undelete_item', as: :undelete_item

    get "settings#{full_path_glob}", action: :settings
    get :settings
    get 'details' => 'courses#settings'
    post :re_send_invitations
    post :enroll_users
    post :link_enrollment
    post :update_nav
    resource :gradebook do
      post 'submissions_upload/:assignment_id' => 'gradebooks#submissions_zip_upload', as: :submissions_upload
      collection do
        get :change_gradebook_version
        get :blank_submission
        get :speed_grader
        post :speed_grader_settings
        get :history
        post :update_submission
        post :change_gradebook_column_size
        post :save_gradebook_column_order
      end
    end

    resource :gradebook_csv, only: [:show]
    get 'gradebook2' => "gradebooks#gradebook2"

    get 'attendance' => 'gradebooks#attendance'
    get 'attendance/:user_id' => 'gradebooks#attendance', as: :attendance_user
    concerns :zip_file_imports

    # DEPRECATED old migration emails pointed the user to this url, leave so the controller can redirect
    get 'imports/list' => 'content_imports#index', as: :import_list
    # DEPRECATED
    get 'imports' => 'content_imports#intro'
    resource :gradebook_upload do
      get 'data' => 'gradebook_uploads#data'
    end
    get 'grades' => 'gradebooks#grade_summary', id: nil
    get 'grading_rubrics' => 'gradebooks#grading_rubrics'
    get 'grades/:id' => 'gradebooks#grade_summary', as: :student_grades
    concerns :announcements
    get 'calendar' => 'calendars#show2', as: :old_calendar
    get :locks
    concerns :discussions
    resources :assignments do
      get 'moderate' => 'assignments#show_moderate'
      resources :submissions do
        post 'turnitin/resubmit' => 'submissions#resubmit_to_turnitin', as: :resubmit_to_turnitin
        get 'turnitin/:asset_string' => 'submissions#turnitin_report', as: :turnitin_report
      end
      get :rubric
      resource :rubric_association, path: :rubric do
        resources :rubric_assessments, path: :assessments

app/views/files/_content_folder.html.erb
<% content_folder ||= nil %>
<li class="content_item folder <%= 'folder_locked' if content_folder && !can_do(content_folder, @current_user, :read_contents) %> <%= 'currently_locked_folder' if content_folder && content_folder.currently_locked %> <%= 'draggable' if can_do(content_folder, @current_user, :update) %>" id="<%= content_folder ? "folder_content_" + content_folder.id.to_s : "folder_content_folder" %>">
  <div class="links">
    <a href="#" class="edit_item_link no-hover" style="<%= "display: none;" unless (can_do(content_folder, @current_user, :update) rescue false) %>"><%= image_tag "edit.png" %></a>
    <a href="#" class="delete_item_link no-hover" style="<%= "display: none;" unless (can_do(content_folder, @current_user, :delete) rescue false) %>"><%= image_tag "delete.png" %></a>
  </div>
  <a href="<%= context_url(@context, :controller => :folders, :action => :update, :id => (content_folder ? content_folder.id : "{{ id }}")) %>" class="name folder_url" title="<%= t 'titles.edit_and_move_instructions', 'Click to edit, drag to move to another folder' %>"><%= content_folder.name rescue "" %></a>
  <div style="display: none;">
    <span class="lock_at"><%= datetime_string(content_file.lock_at) rescue nbsp %></span>
    <span class="unlock_at"><%= datetime_string(content_file.unlock_at) rescue nbsp %></span>
    <span class="last_lock_at"><%= datetime_string(content_file.last_lock_at) rescue nbsp %></span>
    <span class="last_unlock_at"><%= datetime_string(content_file.last_unlock_at) rescue nbsp %></span>
  </div>
  <div class="clear"></div>
</li>

app/views/files/_fields.html.erb
<%= error_messages_for :attachment %>

<p>
  <b><%= t :file, "File" %></b><br/>
  <%= f.file_field :uploaded_data %>
</p>

app/views/files/_folder.html.erb
<% selected ||= false %>
<% folder ||= nil %>
<li id="folder_<%= folder ? folder.id.to_s : "blank" %>" title="<%= folder.name rescue "" %>" class="folder <%= 'folder_locked' if folder && !can_do(folder, @current_user, :read_contents) %> <%= 'currently_locked_folder' if folder && folder.currently_locked %>">
  <div class="folder_name <%= selected ? "selected" : "" %> nobr"><%= folder.name rescue "" %></div>
  <ul class="folder_list" style="display: none;"></ul>
</li>

app/views/files/_nested_content.html.erb
<% skip_ul ||= false; exclude_files ||= false %>
<% unless skip_ul %><ul><% end %>
  <% folders ||= [] %>
  <% nested_content.compact.select{|i| !i.is_a?(Attachment) || !exclude_files}.each do |item|
    new_f = folders.to_a.find{|i| i.id == item.id} if folders && item.is_a?(Folder)
    item = new_f if new_f
    subcontent = folders.select{|f| f.parent_folder_id == f.id } if exclude_files && !folders.empty?
    subcontent ||= item.subcontent(:exclude_files => exclude_files) if item.respond_to?(:subcontent)
  %>
    <li class="<%= item.is_a?(Attachment) ? "file" : "folder" %> <%= 'folder_locked' if item.is_a?(Folder) && item.currently_locked %> <%= item.mime_class rescue "" %> <%= item.is_a?(Attachment) ? "file" : "folder" %>_<%= item ? item.id : "blank" %>">
      <span class="id" style="display: none;"><%= item.id %></span>
      <span class="text name"><%= item.display_name %></span>
      <% if subcontent %>
        <%= render :partial => "files/nested_content", :object => subcontent, :locals => {:exclude_files => exclude_files} %>
      <% end %>
    </li>
  <% end %>
<% unless skip_ul %></ul><% end %>

app/views/files/new.html.erb
<h1><%= t 'titles.upload', "Upload a File" %></h1>
<%= form_for(:attachment, :url => { :action => "create", :format => "json" }, :html => { :multipart => true }) do |f| %>
  <%= render :partial => 'fields', :locals => {:f => f} %>
  <%= f.submit t('buttons.create', "Create") %>
<% end %>

app/views/files/show.html.erb
<% content_for :page_title do %>
  <%= join_title @attachment.display_name, @context.name %>
<% end %>
<% add_crumb @attachment.display_name, context_url(@context, :context_file_url, @attachment) %>
<% download_url = context_url(@context, :context_file_download_url, @attachment.id) %>
<% js_bundle 'module_sequence_footer' %>
<% if !can_do(@attachment.context, @current_user, :manage_files) && (locked = @attachment.locked_for?(@current_user)) %>
  <div style="margin: 10px 50px;">
    <% if @attachment.folder && @attachment.folder.locked? %>
      <%= t 'messages.folder_locked', "The folder \"%{folder},\" which includes this file, has been locked.", :folder => @attachment.folder.name %>
    <% else %>
      <%= locked.is_a?(Hash) ? lock_explanation(locked, 'file', @context) : t('messages.file_locked', "This file has not been unlocked yet.") %>
    <% end %>
  </div>
<% else %>
  <% if @attachment.content_type == "application/x-shockwave-flash" %>
    <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" class="embedded_swf">
      <param name="movie" value="<%= safe_domain_file_url(@attachment) %>" />
      <param name="wmode" value="transparent" />
      <param name="salign" value="t" />
      <param name="allowscriptaccess" value="never" />
      <!--[if !IE]>-->
      <object type="application/x-shockwave-flash" data="<%= safe_domain_file_url(@attachment) %>" class="embedded_swf">
        <param name="wmode" value="transparent" />
        <param name="salign" value="t" />
        <param name="allowscriptaccess" value="never" />
        <!--<![endif]-->
        <!--[if !IE]>-->
      </object>
      <!--<![endif]-->
    </object>
    <a style="display:block;" href="<%= safe_domain_file_url(@attachment, nil, nil, true) %>">Download <%= @attachment.display_name %></a>
  <% elsif @attachment.inline_content? %>
    <% js_bundle :file_inline %>
    <iframe id="file_content" src="<%= safe_domain_file_url(@attachment) %>" style="width: 100%; height: 400px;"></iframe>
  <% elsif @attachment.content_type && @attachment.content_type.match(/\Aimage\//) %>
    <h2><%= @attachment.display_name %></h2>
    <%= link_to(image_tag(download_url, :alt => @attachment.display_name), download_url) %>
  <% elsif @attachment.content_type && @attachment.content_type.match(/\Avideo\/|audio\//) %>
    <% js_bundle :file_preview %>
    <h2><%= @attachment.display_name %></h2>
    <div id="media_preview" <%= media_preview_attributes(@attachment) %>></div>
    <span style="font-size: 1.2em;">
        <%= link_to "Download #{@attachment.display_name}", download_url %>
    </span> (<%= @attachment.readable_size %>)
  <% else %>
    <% js_bundle :file_show %>
    <h2><%= @attachment.display_name %></h2>
    <span style="font-size: 1.2em;">
      <%= link_to "Download #{@attachment.display_name}", download_url %>
    </span> (<%= @attachment.readable_size %>)
    <div id="doc_preview" <%= doc_preview_attributes(@attachment) %>></div>
  <% end %>
<% end %>
<%= render :partial => 'shared/sequence_footer', :locals => {:asset => @attachment} %>

app/views/files/text_show.html.erb
<% content_for :page_title do %><%= t :page_title, "File Preview" %><% end %>

<%= render :partial => "shared/inline_preview" %>